### ISSUE TITLE
VS Code does seem to have Color Preview extension

### ISSUE THREAD

**Issue by lexman1958** [madskristensen/EditorColorPreview#12]
**Describe the bug**
I am unable to locate the Color Preview extension in the latest version of VS Code.
**To Reproduce**
1. Start up VS code
2. Selection Extensions in the sidebar
3. Enter "Color Preview" in the search field
4. No extension shown

**Comment by graymatter00** [comment]
This extension is for Visual Studio 2019 and 2022; not for Visual Studio Code.

See https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ColorPreview

**Comment by lexman1958** [comment]
@graymatter00 Hahaha... did not see that. ChatGPT suggested the extension. The AI is outdated and messing things up. 9 out 10 of my queries all ended up with wrong answers.
