### ISSUE TITLE
VS2022 hangs when openning large CSS file

### ISSUE THREAD

**Issue by mehranrezaei** [madskristensen/EditorColorPreview#13]
When I have this extension enabled VS2022 hangs on opening large CSS files.
My CSS files is about 800KB!

After disabling this extension I can open that file without any problem.

**Comment by ghost** [comment]
I am facing this issue for `.min.css` files. Is possible to ignore those? Usually one does not work with them anyways. But in case of opening one accidentally this bug is pretty annoying.

**Comment by graymatter00** [comment]
@mehranrezaei, @LukeOwlclaw:   This issue might be the same as issue #7, reported in July 2022.
