### ISSUE TITLE
Named colors used in hyphenated variable names show preview

### ISSUE THREAD

**Issue by jeremydeckard** [madskristensen/EditorColorPreview#2]
**When using known color names as part of a variable name, the color preview is applied incorrectly**

**To Reproduce**

Given:

> $hcis-blue: #517ab0;
> $hcis-dark-blue: #015eab;
> $hcis-green: rgb(139, 187, 66);
> $hcis-pink: rgb(216, 73, 124);
> $hcis-yellow: rgb(255, 195, 37);
> 
> $primary: $hcis-blue;
> $danger: $hcis-yellow;
> 
> $dark-gray: #5c5c5c;

Produces:

![image](https://user-images.githubusercontent.com/2386799/153264184-090a5ed7-a933-4ad6-97db-da21c6c81ce1.png)

**Potential fix**

Changing the regular expression to include a non-capturing prefix, e.g. `(?<=.*:.*)(...existing expression...)`, will match only the values on the right side of the colon.

Matches using existing regular expression:

> blue
> #517ab0
> blue
> #015eab
> green
> rgb(139, 187, 66)
> pink
> rgb(216, 73, 124)
> yellow
> rgb(255, 195, 37)
> blue
> yellow
> gray
> #5c5c5c

Matches with suggestion applied:

> #517ab0
> #015eab
> rgb(139, 187, 66)
> rgb(216, 73, 124)
> rgb(255, 195, 37)
> #5c5c5c

These will work as well. 

Given:
> --orange: purple
> 
> span {
>     border: 1px solid red;
> }

Produces:
> purple
> red

**Known issue**

Given:

> span.outline {
>     border: 1px solid red;
> 
>     ::after {
>         content: 'pink';
>         color: blue;
>     }
> }

Produces:

> red
> pink 
> blue

Expected behavior would be to omit 'pink' since it's not a color.

**Comment by jcackowskidiagram** [comment]
This is still an issue if you define a variable with a variable.

Example:

```
$color-blue: $color-different-🟦blue;
```

**Comment by stamminator** [comment]
Issue still taking place

![image](https://user-images.githubusercontent.com/10633170/159782763-c306e9dc-f94d-43c3-90da-7e03d7d14f16.png)

**Comment by stamminator** [comment]
Confirmed fixed in v1.0.9 👍
