### ISSUE TITLE
Add support for TSX/JSX files

### ISSUE THREAD

**Issue by MariaSolOs** [madskristensen/EditorColorPreview#4]
With modern web dev libraries (such as [MUI](https://mui.com/) and [styled-components](https://[styled-components](https://styled-components.com/).com/)) styles are no longer constrained to `.css` files and one can include stylesheets in TSX/JSX files (such as in this [React button](https://mui.com/material-ui/react-button/#CustomizedButtons.tsx) for example). Because this is such a common pattern, it would be great for this extension to also preview the colors in this kind of files.

If this sounds like a good idea I would be happy to work on the implementation! :)

**Comment by madskristensen** [comment]
Fixed in latest release
